=== package-url/purl-spec/schemas/purl-type-definition.schema-1.1.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "$id": "https://packageurl.org/purl-schemas/purl-type-definition.schema-1.1.json",
  "title": "Package-URL Type Definition",
  "description": "Schema to specify a Package-URL (PURL) type as a structured definition.",
  "type": "object",
  "additionalProperties": false,
  "definitions": {
    "optional_requirement": {
      "title": "Component optional requirement",
      "description": "States that this PURL component is optional for a PURL type.",
      "type": "string",
      "const": "optional"
    },
    "recommended_requirement": {
      "title": "Component recommended requirement",
      "description": "States that this PURL component is recommended for a PURL type.",
      "type": "string",
      "const": "recommended"
    },
    "required_requirement": {
      "title": "Component required requirement",
      "description": "States that this PURL component is required for a PURL type.",
      "type": "string",
      "const": "required"
    },
    "prohibited_requirement": {
      "title": "Component prohibited requirement",
      "description": "States that this PURL component is prohibited for a PURL type.",
      "type": "string",
      "const": "prohibited"
    },
    "purl_component_definition": {
      "title": "PURL component definition",
      "description": "PURL component definition properties that apply to most PURL components",
      "type": "object",
      "properties": {
        "permitted_characters": {
          "title": "Permitted characters in this PURL component",
          "description": "A regular expression (ECMA-262 dialect) defining the 'Permitted characters' for this component of this Package-URL type. If provided, this shall be a subset of the 'Permitted characters' defined in the PURL specification.",
          "type": "string",
          "format": "regex"
        },
        "case_sensitive": {
          "title": "Case sensitive",
          "description": "true if this PURL component is case sensitive. If false, the valid form is lowercase.",
          "type": "boolean",
          "default": true
        },
        "normalization_rules": {
          "title": "Normalization rules",
          "description": "List of rules to normalize this component for this PURL type. These are plain text, unstructured rules as some require programming and cannot be enforced only with a schema. Tools are expected to apply these rules programmatically.",
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "native_name": {
          "title": "Native name",
          "description": "The native name of this PURL component in the package ecosystem. For instance, the 'namespace' for the 'maven' type is 'groupId', and 'scope' for the 'npm' PURL type.",
          "type": "string"
        },
        "note": {
          "title": "Note",
          "description": "Extra note text.",
          "type": "string"
        }
      }
    }
  },
  "required": [
    "$id",
    "type",
    "type_name",
    "description",
    "repository",
    "namespace_definition",
    "name_definition",
    "examples"
  ],
  "properties": {
    "$schema": {
      "title": "JSON schema",
      "description": "Contains the URL of the JSON schema for Package-URL type definition.",
      "const": "https://packageurl.org/purl-schemas/purl-type-definition.schema-1.1.json",
      "format": "uri"
    },
    "$id": {
      "title": "PURL type definition id",
      "description": "The unique identifier URI for this PURL type definition.",
      "type": "string",
      "pattern": "^https:\\/\\/packageurl\\.org/purl-types/[a-z0-9-]+-definition\\.json$"
    },
    "type": {
      "title": "PURL type",
      "description": "The type string for this Package-URL type.",
      "type": "string",
      "pattern": "^[a-z][a-z0-9-\\.]+$",
      "examples": [
        "maven",
        "npm",
        "pypi"
      ]
    },
    "type_name": {
      "title": "Type name",
      "description": "The name for this PURL type.",
      "type": "string",
      "examples": [
        "Apache Maven",
        "Python Package"
      ]
    },
    "description": {
      "title": "Description",
      "description": "The description of this PURL type.",
      "type": "string"
    },
    "repository": {
      "title": "Repository",
      "description": "The package repository usage for this PURL type.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "use_repository"
      ],
      "properties": {
        "use_repository": {
          "title": "Use repository",
          "description": "true if this PURL type uses a public package repository.",
          "type": "boolean",
          "default": false
        },
        "default_repository_url": {
          "title": "Default repository URL",
          "description": "The default public repository URL for this PURL type",
          "type": "string",
          "format": "uri"
        },
        "note": {
          "title": "Note",
          "description": "Extra note text.",
          "type": "string"
        }
      }
    },
    "namespace_definition": {
      "title": "Namespace definition",
      "description": "Definition of the namespace component for this PURL type. The PURL namespace component shall be required, optional or prohibited for a specific PURL type definition.",
      "type": "object",
      "required": [
        "requirement"
      ],
      "properties": {
        "requirement": {
          "title": "Namespace requirement",
          "description": "States that the PURL namespace component is optional, required or prohibited for a PURL type.",
          "type": "string",
          "oneOf": [
            {
              "$ref": "#/definitions/optional_requirement"
            },
            {
              "$ref": "#/definitions/required_requirement"
            },
            {
              "$ref": "#/definitions/prohibited_requirement"
            }
          ]
        },
        "registered_values": {
          "title": "Registered namespace values",
          "description": "Optional set of registered namespace values for this PURL type. If the namespace value for a PURL of this type is not one of these registered values, a tool should report a warning. The registered namespace values should be sorted lexicographically.",
          "type": "array",
          "uniqueItems": true,
          "minItems": 1,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "value",
              "description"
          ],
          "properties": {
            "value": {
              "title": "Registered Namespace Value",
              "description": "Registered namespace value for this PURL type.",
              "type": "string"
            },
            "description": {
              "title": "Registered Namespace Description",
              "description": "Explanation of what this namespace value means for this PURL type.",
              "type": "string"
            },
            "reference_url": {
              "title": "Reference URL",
              "description": "Optional Reference URL for where this namespace value is defined for this PURL type.",
              "type":"string"
            }
          }
        }
      }
    },
      "allOf": [
        {
          "$ref": "#/definitions/purl_component_definition"
        }
      ]
    },
    "name_definition": {
      "title": "Name definition",
      "description": "Definition of the name component for this PURL type. The PURL name component is required for all PURL type definitions.",
      "type": "object",
      "required": [
        "requirement"
      ],
      "properties": {
        "requirement": {
          "title": "Name component requirement",
          "description": "States that the PURL name component is always required.",
          "type": "string",
          "oneOf": [
            {
              "$ref": "#/definitions/required_requirement"
            }
          ]
        }
      },
      "allOf": [
        {
          "$ref": "#/definitions/purl_component_definition"
        }
      ]
    },
    "version_definition": {
      "title": "Version definition",
      "description": "Definition of the version component for this PURL type. The PURL version component is optional for a specific PURL type definition.",
      "type": "object",
      "required": [
        "requirement"
      ],
      "properties": {
        "requirement": {
          "title": "Version requirement",
          "description": "States that the PURL version is optional.",
          "type": "string",
          "oneOf": [
            {
              "$ref": "#/definitions/optional_requirement"
            }
          ]
        }
      },
      "allOf": [
        {
          "$ref": "#/definitions/purl_component_definition"
        }
      ]
    },
    "qualifiers_definition": {
      "title": "Qualifiers definition",
      "description": "Definition of the qualifiers specific to this PURL type. The PURL qualifiers component is optional for a specific PURL type, but a qualifiers key or keys may be required for a specific PURL type.",
      "type": "array",
      "additionalItems": false,
      "uniqueItems": true,
      "items": {
        "title": "Qualifiers definition",
        "description": "The definition of a qualifier specific to this PURL type.",
        "type": "object",
        "additionalProperties": false,
        "required": [
          "key",
          "description"
        ],
        "properties": {
          "key": {
            "title": "Qualifier key",
            "description": "The key for the qualifier.",
            "type": "string"
          },
          "requirement": {
            "title": "Qualifier key requirement",
            "description": "States that a PURL qualifier key is optional, recommended or required for a PURL type.",
            "type": "string",
            "oneOf": [
              {
                "$ref": "#/definitions/optional_requirement"
              },
              {
                "$ref": "#/definitions/recommended_requirement"
              },
              {
                "$ref": "#/definitions/required_requirement"
              }
            ]
          },
          "description": {
            "title": "Description",
            "description": "The description of this qualifier key.",
            "type": "string"
          },
          "default_value": {
            "title": "Default value",
            "description": "The optional default value of this qualifier if not provided.",
            "type": "string"
          },
          "native_name": {
            "title": "Native name",
            "description": "The equivalent native name for this qualifier key.",
            "type": "string"
          }
        }
      }
    },
    "subpath_definition": {
      "title": "Subpath definition",
      "description": "The definition for the subpath for this PURL type. The PURL subpath component is optional for a specific PURL type definition.",
      "type": "object",
      "required": [
        "requirement"
      ],
      "properties": {
        "requirement": {
          "title": "Subpath requirement",
          "description": "States that the PURL subpath is optional.",
          "type": "string",
          "oneOf": [
            {
              "$ref": "#/definitions/optional_requirement"
            }
          ]
        }
      },
      "allOf": [
        {
          "$ref": "#/definitions/purl_component_definition"
        }
      ]
    },
    "examples": {
      "title": "PURL examples",
      "description": "Example of valid PURLs for this package type.",
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "string",
        "pattern": "^pkg:[a-z][a-z0-9-\\.]+/.*$"
      }
    },
    "note": {
      "title": "Note",
      "description": "Note about this PURL type.",
      "type": "string"
    },
    "reference_urls": {
      "title": "Reference URLs",
      "description": "Optional list of informational reference URLs about this PURL type.",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "format": "uri"
      }
    }
  }
}

=== package-url/purl-spec/types/oci-definition.json
{
  "$schema": "https://packageurl.org/purl-schemas/purl-type-definition.schema-1.1.json",
  "$id": "https://packageurl.org/purl-types/oci-definition.json",
  "type": "oci",
  "type_name": "OCI image",
  "description": "For artifacts stored in registries that conform to the OCI Distribution Specification https://github.com/opencontainers/distribution-spec including container images built by Docker and others",
  "repository": {
    "use_repository": true,
    "note": "There is no canonical package repository for OCI artifacts. Therefore oci purls shall be registry agnostic by default. To specify the repository, provide a repository_url value."
  },
  "namespace_definition": {
    "requirement": "prohibited",
    "note": "OCI purls do not contain a namespace, although, repository_url may contain a namespace as part of the physical location of the package."
  },
  "name_definition": {
    "requirement": "required",
    "case_sensitive": false,
    "note": "The name is not case sensitive and shall be lowercased. The name is the last fragment of the repository name. For example if the repository name is library/debian then the name is debian."
  },
  "version_definition": {
    "requirement": "optional",
    "case_sensitive": false,
    "note": "The version is the sha256:hex_encoded_lowercase_digest of the artifact and is required to uniquely identify the artifact."
  },
  "qualifiers_definition": [
    {
      "key": "arch",
      "description": "key for a package architecture, when relevant."
    },
    {
      "key": "repository_url",
      "description": "A repository URL where the artifact may be found, but not intended as the only location. This value is encouraged to identify a location the content may be fetched."
    },
    {
      "key": "tag",
      "description": "artifact tag that may have been associated with the digest at the time."
    }
  ],
  "reference_urls": [
    "https://github.com/opencontainers/distribution-spec"
  ],
  "examples": [
    "pkg:oci/debian@sha256%3A244fd47e07d10?repository_url=docker.io%2Flibrary%2Fdebian&arch=amd64&tag=latest",
    "pkg:oci/debian@sha256%3A244fd47e07d10?repository_url=ghcr.io%2Fdebian&tag=bullseye",
    "pkg:oci/static@sha256%3A244fd47e07d10?repository_url=gcr.io%2Fdistroless%2Fstatic&tag=latest",
    "pkg:oci/hello-wasm@sha256:244fd47e07d10?tag=v1"
  ]
}

=== package-url/purl-spec/types/composer-definition.json
{
  "$schema": "https://packageurl.org/purl-schemas/purl-type-definition.schema-1.1.json",
  "$id": "https://packageurl.org/purl-types/composer-definition.json",
  "type": "composer",
  "type_name": "Composer",
  "description": "Composer PHP packages",
  "repository": {
    "use_repository": true,
    "default_repository_url": "https://packagist.org"
  },
  "namespace_definition": {
    "requirement": "required",
    "case_sensitive": false,
    "native_name": "vendor",
    "note": "The namespace is the vendor. The namespace is not case sensitive and shall be lowercased."
  },
  "name_definition": {
    "requirement": "required",
    "case_sensitive": false,
    "native_name": "name",
    "note": "The name is not case sensitive and shall be lowercased. Private, local packages may have no name. In this case you cannot create a purl for these."
  },
  "version_definition": {
    "requirement": "optional",
    "native_name": "version"
  },
  "examples": [
    "pkg:composer/laravel/laravel@5.5.0"
  ]
}

=== package-url/purl-spec/types/chrome-extension-definition.json
{
  "$schema": "https://packageurl.org/purl-schemas/purl-type-definition.schema-1.1.json",
  "$id": "https://packageurl.org/purl-types/chrome-definition.json",
  "type": "chrome-extension",
  "type_name": "Chrome Browser Extensions",
  "description": "Chrome Browser Extensions. Note: there are currently no officially documented APIs, further there appears to be no way to query different versions of a package - there only seems to be responses on the latest version. To this end the version component of a chrome purl can be optional. Two known data sources are a sitemap which can be crawled to discover (some) extensions at https://chromewebstore.google.com/sitemap, and an 'updatecheck' API which you can read about here https://github.com/Rob--W/crxviewer , and perhaps here https://github.com/chromium/chromium/blob/main/docs/updater/protocol_3_1.md",
  "repository": {
    "use_repository": true,
    "default_repository_url": "https://chromewebstore.google.com/",
    "note": "There is no documented API, only a sitemap and 'updatecheck' endpoints."
  },
  "namespace_definition": {
    "requirement": "prohibited",
    "note": "There is no namespace"
  },
  "name_definition": {
    "native_name": "extension_id",
    "requirement": "required",
    "permitted_characters": "^[a-p]{32}$",
    "case_sensitive": false,
    "note": "The name is 32 characters in the range a-p (base16-encoded with letters instead of hex digits) and is case insensitive. This is not the same as the display name which is human readable and may vary with locale."
  },
  "version_definition": {
    "native_name": "version",
    "requirement": "optional",
    "permitted_characters": "^\\d+(\\.\\d+){0,3}$",
    "note": "The chrome extension version is semver-like but 1-4 segments. See https://developer.chrome.com/docs/extensions/reference/manifest/version"
  },
  "examples": [
    "pkg:chrome-extension/hlepfoohegkhhmjieoechaddaejaokhf@25.7.1",
    "pkg:chrome-extension/dncgedbnidfkppmdgfgidcepclnokpkb@6.0.2.3611",
    "pkg:chrome-extension/kanfjhdeebkfgkbmnfknhejpadhlmiab@0.6",
    "pkg:chrome-extension/dlpngalgnefjeiefhmpklpfiohadpglk@1",
    "pkg:chrome-extension/dlpngalgnefjeiefhmpklpfiohadpglk"
  ]
}

=== package-url/purl-spec/types/bitnami-definition.json
{
  "$schema": "https://packageurl.org/purl-schemas/purl-type-definition.schema-1.1.json",
  "$id": "https://packageurl.org/purl-types/bitnami-definition.json",
  "type": "bitnami",
  "type_name": "Bitnami",
  "description": "Bitnami-based packages",
  "repository": {
    "use_repository": true,
    "default_repository_url": "https://downloads.bitnami.com/files/stacksmith"
  },
  "namespace_definition": {
    "requirement": "prohibited",
    "note": "there is no namespace"
  },
  "name_definition": {
    "requirement": "required",
    "note": "The name is the component name. It shall be lowercased.",
    "case_sensitive": false,
    "native_name": "name"
  },
  "version_definition": {
    "requirement": "optional",
    "native_name": "full package version, including version and revision",
    "note": "The version is the full Bitnami package version, including version and revision."
  },
  "qualifiers_definition": [
    {
      "key": "arch",
      "description": "The arch is the qualifiers key for a package architecture. Available values are amd64 (default) and arm64.",
      "default_value": "amd64"
    },
    {
      "key": "distro",
      "description": "The distro is the qualifiers key for the distribution associated to the package."
    }
  ],
  "examples": [
    "pkg:bitnami/wordpress?distro=debian-12",
    "pkg:bitnami/wordpress@6.2.0?distro=debian-12",
    "pkg:bitnami/wordpress@6.2.0?arch=arm64&distro=debian-12",
    "pkg:bitnami/wordpress@6.2.0?arch=arm64&distro=photon-4"
  ]
}

=== package-url/purl-spec/types/generic-definition.json
{
  "$schema": "https://packageurl.org/purl-schemas/purl-type-definition.schema-1.1.json",
  "$id": "https://packageurl.org/purl-types/generic-definition.json",
  "type": "generic",
  "type_name": "Generic Package",
  "description": "The generic type is for plain, generic packages that do not fit anywhere else such as for \"upstream-from-distro\" packages. In particular this is handy for a plain version control repository such as a bare git repo in combination with a vcs_url.",
  "repository": {
    "use_repository": false,
    "note": "There is no default repository."
  },
  "namespace_definition": {
    "requirement": "optional",
    "note": "there is no generic namespace definition"
  },
  "name_definition": {
    "requirement": "required",
    "note": "as for other type, the name component is mandatory. In the worst case it can be a file or directory name."
  },
  "qualifiers_definition": [
    {
      "key": "download_url",
      "description": "A download_url and checksum may be provided in qualifiers or as separate attributes outside of a purl for proper identification and location."
    },
    {
      "key": "checksum",
      "description": "A checksum may be provided in qualifiers or as separate attributes outside of a purl for proper identification and location."
    }
  ],
  "note": "When possible another or a new purl type should be used instead of using the generic type and eventually contributed back to this specification. Example have been truncated for brevity",
  "examples": [
    "pkg:generic/openssl@1.1.10g",
    "pkg:generic/openssl@1.1.10g?download_url=https:%2F%2Fopenssl.org%2Fsource%2Fopenssl-1.1.0g.tar.gz&checksum=sha256:de4d501267da",
    "pkg:generic/bitwarderl?vcs_url=git%2Bhttps:%2F%2Fgit.fsfe.org%2Fdxtr%2Fbitwarderl%40cc55108da32"
  ]
}

=== package-url/purl-spec/types/cran-definition.json
{
  "$schema": "https://packageurl.org/purl-schemas/purl-type-definition.schema-1.1.json",
  "$id": "https://packageurl.org/purl-types/cran-definition.json",
  "type": "cran",
  "type_name": "CRAN",
  "description": "CRAN R packages",
  "repository": {
    "use_repository": true,
    "default_repository_url": "https://cran.r-project.org"
  },
  "namespace_definition": {
    "requirement": "prohibited",
    "note": "there is no namespace"
  },
  "name_definition": {
    "requirement": "required",
    "native_name": "name",
    "case_sensitive": true,
    "note": "The name is the package name and is case sensitive, but there cannot be two packages on CRAN with the same name ignoring case."
  },
  "version_definition": {
    "requirement": "optional",
    "native_name": "version",
    "note": "The version is the package version."
  },
  "examples": [
    "pkg:cran/A3@1.0.0",
    "pkg:cran/rJava@1.0-4",
    "pkg:cran/caret@6.0-88"
  ]
}

=== package-url/purl-spec/types/maven-definition.json
{
  "$schema": "https://packageurl.org/purl-schemas/purl-type-definition.schema-1.1.json",
  "$id": "https://packageurl.org/purl-types/maven-definition.json",
  "type": "maven",
  "type_name": "Maven",
  "description": "PURL type for Maven JARs and related artifacts.",
  "repository": {
    "use_repository": true,
    "default_repository_url": "https://repo.maven.apache.org/maven2/",
    "note": "The Maven Central repository is the public repository for Apache Maven packages. This repository is also mirrored at https://repo1.maven.org/maven2/. Use the standard repository_url qualifier to point to another repository"
  },
  "namespace_definition": {
    "requirement": "required",
    "case_sensitive": true,
    "native_name": "groupId",
    "note": "The group id is the namespace."
  },
  "name_definition": {
    "requirement": "required",
    "case_sensitive": true,
    "native_name": "artifactId",
    "note": "The artifact id is the name."
  },
  "version_definition": {
    "requirement": "optional",
    "case_sensitive": true,
    "native_name": "version"
  },
  "qualifiers_definition": [
    {
      "key": "classifier",
      "requirement": "optional",
      "description": "The maven classifier as defined in the POM documentation.",
      "native_name": "classifier"
    },
    {
      "key": "type",
      "requirement": "optional",
      "description": "The maven type as defined in the POM documentation. Note that Maven uses a concept / coordinate called packaging which does not map directly 1:1 to a file extension. In this use case, we need to construct a link to one of many possible artifacts. Maven itself uses type in a dependency declaration when needed to disambiguate between them.",
      "native_name": "type",
      "default_value": "jar"
    }
  ],
  "examples": [
    "pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1",
    "pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1?type=pom",
    "pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1?classifier=sources",
    "pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1?type=zip&classifier=dist",
    "pkg:maven/net.sf.jacob-projec/jacob@1.14.3?classifier=x86&type=dll",
    "pkg:maven/net.sf.jacob-projec/jacob@1.14.3?classifier=x64&type=dll",
    "pkg:maven/groovy/groovy@1.0?repository_url=https:%2F%2Fmaven.google.com"
  ]
}

=== package-url/purl-spec/types/rpm-definition.json
{
  "$schema": "https://packageurl.org/purl-schemas/purl-type-definition.schema-1.1.json",
  "$id": "https://packageurl.org/purl-types/rpm-definition.json",
  "type": "rpm",
  "type_name": "RPM",
  "description": "RPM packages",
  "repository": {
    "use_repository": true,
    "note": "There is no default package repository, this should be implied either from the distro qualifiers key or using a repository base URL as repository_url qualifiers key."
  },
  "namespace_definition": {
    "case_sensitive": false,
    "native_name": "vendor",
    "note": "The namespace is the vendor such as Fedora or OpenSUSE. It is not case sensitive and shall be lowercased.",
    "requirement": "required"
  },
  "name_definition": {
    "requirement": "required",
    "case_sensitive": true,
    "note": "The name is the RPM name and is case sensitive.",
    "native_name": "name"
  },
  "version_definition": {
    "requirement": "optional",
    "note": "The version is the combined version and release of an RPM.",
    "native_name": "version-release"
  },
  "qualifiers_definition": [
    {
      "key": "epoch",
      "requirement": "optional",
      "description": "(optional for RPMs) is a qualifier as its not required for unique identification, but when the epoch exists we strongly encourage using it."
    },
    {
      "key": "arch",
      "description": "the qualifiers key for a package architecture."
    }
  ],
  "examples": [
    "pkg:rpm/fedora/curl@7.50.3-1.fc25?arch=i386&distro=fedora-25",
    "pkg:rpm/fedora/centerim@4.22.10-1.el6?arch=i686&epoch=1&distro=fedora-25"
  ]
}
